GET http://localhost:5224/weatherforecast/
Accept: application/json

###
GET http://localhost:5224/api/Categories
Accept: application/json


### Send POST request with json body

POST http://localhost:5224/api/Categories
Content-Type: application/json

{
  "name": "test1",
  "urlHandle": "test-1"
}
