GET http://localhost:5224/weatherforecast/
Accept: application/json

###
GET http://localhost:5224/api/Categories
Accept: application/json

###
GET http://localhost:5224/api/Categories/f0502c58-fce1-4d72-e2ad-08ded91a6775aa
Accept: application/json

### Send POST request with json body

POST http://localhost:5224/api/Categories
Content-Type: application/json

{
  "name": "test1",
  "urlHandle": "test-1"
}

### 

PUT http://localhost:5224/api/Categories/a28473a6-4587-4023-145e-08ded6ea33d2
Content-Type: application/json

{
  "name": "آقا اسدی برزگ",
  "urlHandle": "fromPut"
}

###
DELETE http://localhost:5224/api/Categories/524d927e-dab0-4e34-1ee4-08ded73c3d58
Content-Type: application/json


### Send POST request with json body

POST http://localhost:5224/api/BlogPosts
Content-Type: application/json

{
  "author": "test",
  "content": "متحپای زیاد",
  "featuredImageUrl": "https://test.com/img.jpeg",
  "isVisible": true,
  "publishedDate": "2026-07-13",
  "shortDescription": "توضیح...",
  "title": "تست",
  "urlHandle": "test"
}

###
GET http://localhost:5224/api/BlogPosts
Accept: application/json
